apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
  name: java-deployment-rd2wn
  namespace: default
spec:
  ports:
  - name: tcp1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcp2
    port: 4848
    protocol: TCP
    targetPort: 4848
  - name: tcp3
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: java
  type: LoadBalancer
